name: DESTROY

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: sa-east-1
  AWS_ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}

jobs:
  nuke:
    runs-on: ubuntu-latest
    environment: sandbox   # proteja com reviewers no GitHub
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/gha-oidc-terraform
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform destroy
        working-directory: infra
        run: |
          terraform init -input=false
          terraform destroy -auto-approve -input=false
